spring:
  application:
    name: ideas
#  datasource: 
#    url: ${JDBC_DATABASE_URL}
#    username: ${JDBC_DATABASE_USERNAME}
#    password: ${JDBC_DATABASE_PASSWORD}
server:
  context-path: /
  port: 8080